### ISSUE TITLE
请教：怎样把这个项目打包成bin文件

### ISSUE THREAD

**Issue by 1003657663** [Caffreyfans/IRbaby-firmware#11]
我看了一下，项目里没有.ino文件，即使有，这个项目结构似乎也不能用arduino打包。

请教作者，这个项目是用什么工具，执行什么命令可以打包成bin文件呀

**Comment by Caffreyfans** [comment]
这个是用的 Platformio 开发框架开发的, 详情请见 [Platformio 官方](https://docs.platformio.org/en/latest/platforms/espressif8266.html)
